### ISSUE TITLE
Investigate venue options in / near edinburgh

### ISSUE THREAD

**Issue by mattwynne** [mattwynne/bootstrapd#1]

**Comment by tooky** [comment]
[South Hall Complex](http://www.edinburghfirst.co.uk/venues/south-hall-complex?type=ForResidential&layout=classroom&breakouts=3&attending=30&selected=1234&back=1)

**Comment by mattwynne** [comment]
Paul suggested these:

http://www.eica-ratho.com/content/-conferences/2418/
http://www.hopetoun.co.uk/conferences-and-meetings.html

I'll ping a couple of local mailing lists.

**Comment by mattwynne** [comment]
Does South Hall have space on the date we want?

**Comment by mattwynne** [comment]
> From: Gordon Guthrie gordon@hypernumbers.com
> Subject: Re: [scot lean circle] Suggestions for conference venue
> Date: 6 March 2012 16:04:57 GMT
> To: edleanstartup@googlegroups.com
> Reply-To: edleanstartup@googlegroups.com
> 
> Matt
> 
> A pal of mine has a beautiful place right on the train station at Pitlochry:
> http://www.observatorypitlochry.com/galleries.htm
> 
> Huge main room (60 foot by 20 feet), beds for 8, a few acres of land
> for the camping type.
> 
> Gordon

**Comment by tooky** [comment]
http://www.edinburghfirst.co.uk/

**Comment by tooky** [comment]
Bletchley Park?

**Comment by tooky** [comment]
Edinburgh First are putting together a proposal for [Abden House](http://www.edinburghfirst.co.uk/venues/abden-house)

Its a building that we can get exclusive use of, including gardens if its a nice day.

Main room sits 50 theatre style - so should be ok for 30-40 in more informal seating. It has various smaller rooms for break out spaces.

Day delegate rate is £39 inc. VAT. Includes basic AV and WIFI.

Its available on both the 26th and 27th.

They are coming back to me with accommodation / dinner the night before options.

**Comment by mattwynne** [comment]
Accom is £74, dinner is £28.

**Comment by mattwynne** [comment]
I just rang round all the other venues I'd shortlisted in Edinburgh. They either didn't answer the phone or aren't suitable, so it looks like Abden house is our best bet.
