### ISSUE TITLE
Issue scholarships

### ISSUE THREAD

**Issue by mattwynne** [mattwynne/bootstrapd#24]
Here's how I'm thinking this will work:
- We set up a discount code on eventbrite for 10 tickets at 50% off.
- We set up a google form to ask people:
  1. What's your email?
  2. Tell us about the product you're building. Who is it for? What does it do for them?
  3. In 50 words or less, Why do you think you deserve the scholarship?
- We email the edleanstartup and manchester bootstrappers club groups with links to the form
- We sit back and wait for some good replies, and email the code to the first 10 good answers.

We could do it via twitter I guess, but 140 chars might not be enough to establish their bootstrapping credentials. WDYT?

**Comment by tooky** [comment]
I've put a form up at http://bootstrapd.com/scholarship.html.

I'm pretty sure @mattwynne has no internet for the next week, but just in case - I'll wait until tomorrow before contacting the two groups.
