### ISSUE TITLE
Price up / check availability of Ross Priory

### ISSUE THREAD

**Issue by mattwynne** [mattwynne/bootstrapd#3]

**Comment by mattwynne** [comment]
Ross Priory Sleeps 11 + 6 so we'd need other accom in Glasgow or Drymen,
112 / person for 24 hours.

Does it have availability?

**Comment by tooky** [comment]
There are only 6 rooms available on the 27th / June so can only offer 9-5 availability of meeting room.

The largest room seats 60 theatre style, so would be comfortable for about 30 or so with breakout areas spread around the room.

Day delegate rate is £49.20 per person including coffee / lunch

**Comment by mattwynne** [comment]
We could stay here, which is nearby (5 mins in a cab)
http://www.winnockhotel.com/

They have tons of rooms.

**Comment by mattwynne** [comment]
However, if we can't stay in Ross Priory, it somewhat defeats the object of making it feel like a 'retreat', and maybe we should for an alternative nearer to Edinburgh.WDYT?

**Comment by mattwynne** [comment]
Not using Ross Priory unless we change the date.
