### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by mattwynne** [mattwynne/bootstrapd#30]
I can't work out why. http://mattwynne.github.com/bootstrapd doesn't give me anything. Any ideas?

**Comment by tooky** [comment]
I can see the main site has come back up. Not sure why the github link isn't working?

## 

Steve Tooke :: heavi.es
+44 7919 337 463 :: +44 20 8133 4134
skype:stevetooke :: twitter.com/tooky

Heavies Limited
Registered Number: 7612561
Registered Address: Parmenter House, 57 Tower Street, Winchester SO23 8TD

**Comment by mattwynne** [comment]
I pushed a one-line commit, which must have fixed it. Seems like Github pages is a bit flakey... Anyway, closing this ticket.
