### ISSUE TITLE
Reach out to Famous People

### ISSUE THREAD

**Issue by mattwynne** [mattwynne/bootstrapd#5]
amy hoy
peter cooper
-- but offer no fee

**Comment by mattwynne** [comment]
I notice @peterc is coming to speak at scotlandjs, so there's a likelyhood we could persuade him to come to ours too if we can get on with it.

**Comment by peterc** [comment]
I learnt something funny about GitHub today. If you @ mention someone, they get an e-mail about it even if it's on a project they have nothing to do with! ;-) I got your e-mail, by the way. I might! I need to ask you for more info about the event.

And no, no fee required ;-) I'll be in town anyway and I'm mostly interested in your event being awesome.

**Comment by mattwynne** [comment]
Ha ha ha!

It would be great to hear what questions you have, as I'm going to start working on a proper website for the conf, so your questions can help me drive the content.

**Comment by peterc** [comment]
Weird, I thought you e-mailed me about this but I might be wrong.. can't find it. Did you? Or was it someone else? Either way, I seem to have lost it :-(

In any case, can you drop me an e-mail to my GitHub associated e-mail (just to avoid the scrapers here..) and flesh out what your plans/what the day is going to be like, etc? :-)

**Comment by mattwynne** [comment]
Hey Peter,

On 15 Apr 2012, at 00:32, Peter Cooper wrote:

> Weird, I thought you e-mailed me about this but I might be wrong.. can't find it. Did you? Or was it someone else? Either way, I seem to have lost it :-(

We sent out a mailshot a couple of days ago to everyone who'd signed up on the eventbrite page, that had quite a bit of detail on it. Maybe that's what you're talking about.

> In any case, can you drop me an e-mail to my GitHub associated e-mail (just to avoid the scrapers here..) and flesh out what your plans/what the day is going to be like, etc? :-)

Sure, will do that ASAP. The new site is live at http://bootstrapd.com might have slightly more detail than the launchrock one. I'm also working on a press release today which I'll forward to you.

Thanks for your encouragement so far :)

cheers,
Matt

## 

Freelance programmer & coach
Author, http://pragprog.com/book/hwcuc/the-cucumber-book
Founder, http://www.relishapp.com/
Twitter, https://twitter.com/mattwynne
